// src/Web/react-app/src/components/apps/AppList.tsx
import { Link, useNavigate } from "react-router-dom";
import { Button } from "flowbite-react";
import appData from "../../data/apps.json";
import App from "./App";
import { useEffect, useState } from "react";

export default function AppList() {
  const location = useNavigate();
  const [apps, setApps] = useState<App[]>([]);
  useEffect(() => {
    setTimeout(() => {
      const apps = appData as App[];
      setApps(apps);
    }, 100);
  }, []);
  return (
    <div className="mx-auto mt-2 max-w-4xl p-2">
      <div className="flex items-center">
        <h1 className="font-semibold">Your Apps</h1>
        <Button
          size="sm"
          className="ms-auto"
          onClick={() => location("/apps/new")}
        >
          New
        </Button>
      </div>
      <form className="mt-2">
        <label
          htmlFor="search-input"
          className="sr-only mb-2 text-sm font-medium text-gray-900 dark:text-white"
        >
          Search
        </label>
        <div className="relative">
          <input
            type="text"
            id="search-input"
            className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
          />
        </div>
      </form>
      <ul className="mt-3">
        {apps.map((app) => {
          return (
            <li key={app.id}>
              <div className="mb-2">
                <Link to={`/apps/${app.id}`} className="text-slate-900">
                  {app.name}
                </Link>
                <p>{app.description}</p>
                <p className="text-gray text-sm font-light">
                  Created: {new Date(app.createdAt).toDateString()}
                </p>
              </div>
            </li>
          );
        })}
      </ul>
    </div>
  );
}

// src/Web/WebSPA/src/components/AppList.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import AppItem from '../AppItem';
import { watch } from 'vue';
import debounce from '../helper';
import moment from 'moment';

const loading = ref(true);

const apps = ref<AppItem[]>([])

onMounted(() => {
    fetchApps(undefined);
})

const searchTerm = ref();
const debouncedSearch = debounce(() => {
    fetchApps(searchTerm.value);
}, 1000);
watch(searchTerm, () => {
    debouncedSearch();
})

function fetchApps(searchTerm: string | undefined) {
    console.log('fetchApps:', searchTerm);
    setTimeout(() => {
        const items: AppItem[] = [];
        for (let index = 1; index <= 10; index++) {
            items.push({ id: index, name: `App ${index}`, description: `App ${index}`, createdAt: new Date() });
        }
        apps.value = items;
        loading.value = false;
    }, 1000)
}

</script>

<template>
    <div>
        <h1 class="text-lg font-bold">Your Apps</h1>
        <div class="flex mt-2">
            <div>
                <input type="search" v-model="searchTerm" class="p-2 border rounded-md focus:outline-none" placeholder="Search apps..." />
            </div>
            <div class="ms-auto">
                <RouterLink to="/apps/new" class="ms-auto">
                    <button type="button" class="p-2 bg-violet-600 text-white rounded-md">New</button>
                </RouterLink>
            </div>
        </div>
        <div v-if="!loading" class="mt-5">
            <div v-if="apps.length === 0">You don't have any app. Create one.</div>
            <ul v-else role="list" class="p-2">
                <li role="listitem" v-for="app in apps" :key="app.id" class="p-2">
                    <div class="pb-3">
                        <h3 class="text-lg text font-semibold text-blue-500"><RouterLink :to="`/apps/${app.id}`">{{ app.name }}</RouterLink></h3>
                        <p class="text-sm">{{ app.description }}</p>
                        <p class="text-sm text-slate-500">Created {{ moment(app.createdAt).fromNow() }}</p>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</template>
