// src/Web/WebSPA/src/modules/app/views/AppList.vue
<template>
    <div class="h-full max-w-screen-lg mx-auto p-2">
        <div class="mt-4 px-3 flex flex-row">
            <h1 class="text-lg font-semibold">Your Apps</h1>
            <RouterLink :to="{ name: 'AppCreate' }" class="ms-auto">
                <FwbButton>New</FwbButton>
            </RouterLink>
        </div>
        <form class="mt-3 flex items-center">
            <label for="simple-search" class="sr-only">Search</label>
            <input type="text" id="simple-search" v-model="searchTerm"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Search apps...">
        </form>
        <div v-if="!loading" class="mt-5">
            <div v-if="apps.length === 0">You don't have any app. Create one.</div>
            <ul v-else role="list" class="divide-y">
                <li role="listitem" v-for="app in apps" :key="app.id" class="p-2">
                    <div class="pb-3">
                        <h3 class="text-lg text font-semibold text-blue-500">
                            <RouterLink :to="`/app/${app.id}`">{{ app.name }}</RouterLink>
                        </h3>
                        <p class="text-sm">{{ app.description }}</p>
                        <p class="text-sm text-slate-500">Created {{ moment(app.createdAt).fromNow() }}</p>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { watch } from 'vue';
import moment from 'moment';
import AppItem from '../models/AppItem';
import debounce from '@/modules/core/utils';
import { FwbButton } from 'flowbite-vue';
import { useAppStore } from '../store/appStore';

const { getApps } = useAppStore();

const loading = ref(true);

const apps = ref<AppItem[]>([])

onMounted(async () => {
    await fetchApps(undefined);
})

const searchTerm = ref();
const debouncedSearch = debounce(async () => {
    await fetchApps(searchTerm.value);
}, 1000);

watch(searchTerm, () => {
    debouncedSearch();
})

async function fetchApps(searchTerm: string | undefined) {
    apps.value = await getApps();
    loading.value = false;
}
</script>

// src/Web/WebApp/src/components/apps/AppList.tsx
import { Link } from "react-router-dom";
import App from "./App";
import { useEffect, useState } from "react";
import { useAuth0 } from "@auth0/auth0-react";

export default function AppList() {
  const [searchTerm, setSearchTerm] = useState("");
  const [apps, setApps] = useState<App[]>([]);
  const { getAccessTokenSilently } = useAuth0();

  const getApps = async () => {
    const accessToken = await getAccessTokenSilently();
    const res = await fetch(`/api/apps?term=${searchTerm}`, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    });
    const apps = (await res.json()) as App[];
    setApps(apps);
  };

  useEffect(() => {
    //TODO: debounce
    getApps();
  }, [searchTerm]);
  return (
    <div className="mx-auto mt-2 max-w-4xl p-2">
      <div className="flex items-center">
        <h1 className="font-semibold">Apps</h1>
        <Link
          to={"new"}
          className="group relative ms-auto flex items-center justify-center border border-transparent bg-primary p-0.5 text-center font-medium text-white focus:z-10 focus:outline-none focus:ring-2 focus:ring-cyan-300 enabled:hover:bg-cyan-800 dark:bg-cyan-600 dark:focus:ring-cyan-800 dark:enabled:hover:bg-cyan-700"
        >
          <span className="flex items-center rounded-md px-3 py-1 text-sm transition-all duration-200">
            New
          </span>
        </Link>
      </div>
      <form className="mt-2">
        <label
          htmlFor="search-input"
          className="sr-only mb-2 text-sm font-medium text-gray-900 dark:text-white"
        >
          Search
        </label>
        <input
          type="text"
          id="search-input"
          onChange={(e) => {
            setSearchTerm(e.target.value);
          }}
          placeholder="Search..."
          className="block w-full border border-gray-300 bg-gray-50 p-1.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
        />
      </form>
      <ul className="mt-3 divide-y">
        {apps.map((app) => {
          return (
            <li key={app.id}>
              <div className="mb-2">
                <h4>
                  <Link
                    to={`${app.id}/overview`}
                    className="font-semibold text-slate-900"
                  >
                    {app.name}
                  </Link>
                  <small
                    className={`ms-1 ${
                      app.status === "Active"
                        ? "text-green-500"
                        : "text-red-500"
                    }`}
                  >
                    {app.status}
                  </small>
                </h4>
                <p className="text-sm text-slate-600">{app.description}</p>
                <small className="text-sm text-slate-600">
                  Created: {new Date(app.createdAt).toDateString()}
                </small>
              </div>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
